### ISSUE TITLE
Appendix F.2 and F.3 should acknowledge alternative notations

### ISSUE THREAD

**Issue by cbm755** [arechnitzer/CLP4#25]
Some of us are engineers, you insensitive clods, please acknowledge there are other choices for radius and angle.

Our preferences for cylindrical are "rho" for distance and "phi" for angle.

kthxbye

**Comment by arechnitzer** [comment]
I guess it cannot be helped that some people will be engineers, so I agree that we should put in something to help the poor lost souls.

**Comment by cbm755** [comment]
@ParsaBan @call-me-Icarus can either of you provide a reference for what the various "standards" for spherical coordinates actually are?  And which communities use which "standard"?

I.e., many people throw around terms like "Engineering Notation", "Physics Notation"...

**Comment by arechnitzer** [comment]
We have a draft appendix that describes ISO-80000 standard 
https://en.wikipedia.org/wiki/ISO/IEC_80000

**Comment by arechnitzer** [comment]
This has been fixed in the most recent jdev merge. Closing.
